Init CHANGELOG.md
curl/wcurl pull request #33
Opened 2024-12-07 19:42 UTC by samueloph

2024-12-07 23:44 UTC, sergiodj requested changes
Thanks, @samueloph.

I left some comments and requests for change, but the file is looking good.

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Second release.
Not that it matters much, but would you like to add some information on what changed here?

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Drop getotp usage, non-linux environments are supported now.
- `s/getotp/getopt/`

- Use backticks on `getopt`.

- I will personally use "GNU/Linux", but it's OK if you don't want to.  However, I believe we should at least capitalize the name "Linux" here.

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Replace "-o/--opts=" parameters with "--curl-options/--curl-options=".
Since this file is explicitly written in Markdown, we should use backticks here and elsewhere.

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> +   One can easily change that behavior with '--curl-options="--continue-at -'.
There's a mix of single and double quotes here (but we should use backticks).

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Choose https as a default protocol, in case there's none in the URL.
`s/https/HTTPS/`.

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Implement a -V and --version options.
```suggestion
 * Implement `-V/--version` options.
```

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> +     - Only set --parallel if curl is 7.66 or newer
Missing period at the end of this sentence and the previous one.

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Set --fail on curl, in order to return errors instead of saving as
```suggestion
 * Set `--fail` when invoking curl, in order to display possible errors instead of saving them as
```

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * wcurl.1: Update manpage with links to Github and Debian's Salsa.
This format of `file: what changed` isn't used anywhere else, so I think we shouldn't use it here either.

2024-12-07 23:44 UTC, sergiodj commented on CHANGELOG.md
> + * Default to index.html as filename if non can be parsed from the URL.
I think there's some typo here...?  I don't fully understand the sentence.

2024-12-08 18:59 UTC, samueloph commented
> Thanks, @samueloph.
> 
> I left some comments and requests for change, but the file is looking good.

Thank you @sergiodj, I believe I have addressed all of them with the latest changes.

2024-12-08 22:07 UTC, sergiodj requested changes
Thanks, @samueloph.

I'm leaving a second round of suggestions that are ready to be applied.  Feel free to merge the PR afterwards.

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Default to "index.html" as filename if none can be inferred from the URL.
```suggestion
 * Default to `index.html` as filename if none can be inferred from the URL.
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> +     - New version: 2024.07.10
```suggestion
     - Previous version: `2024-07-07`
     - New version: `2024.07.10`
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Remove the need for GNU coreutils' realpath for tests.
```suggestion
 * Remove the need for GNU coreutils' `realpath` for tests.
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Implement support for `--`'.
```suggestion
 * Implement support for `--`.
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Rewrite wcurl to remove bash dependency, it's now a POSIX shellscript.
```suggestion
 * Rewrite wcurl to remove bash dependency, it's now a POSIX shell script.
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Simplify`--help` output.
```suggestion
 * Simplify `--help` output.
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Replace `-o/--opts=` parameters with `--curl-options/--curl-options=`.
```suggestion
 * Replace `-o`/`--opts=` parameters with `--curl-options`/`--curl-options=`.
```

2024-12-08 22:07 UTC, sergiodj commented on CHANGELOG.md
> + * Implement `-V/--version` options.
```suggestion
 * Implement `-V`/`--version` options.
```

2024-12-08 22:54 UTC, merged